[tool.black]
line-length = 128

[tool.isort]
profile = "black"
force_grid_wrap = 0
include_trailing_comma = "true"
line_length = 128
lines_after_imports = 2
multi_line_output = 3
use_parentheses = "true"
ensure_newline_before_comments = "true"