openapi: 3.1.0
info:
  title: Translation Inference Service
  description: |-
    This project aims to implement a translation inference service that runs on Kubernetes and provides a RESTful API on port 9527.

    Utilizing the `M2M100` translation model, this service is capable of translating text, accessible through a simple HTTP request.

    The primary goal of this project is to create a scalable and efficient translation service that can fully leverage CPU and GPU resources for optimal performance.
  version: 1.0.0
paths:
  "/translation/":
    post:
      summary: Translation
      description: |-
        Translate Text from Source Language to Target Language

        This endpoint provides a translation service using the M2M100 model. It accepts a request containing the source text,
        source language (fromLang), and target language (toLang), along with other details. The translation is performed,
        and the translated text is returned in the response.

        **Notes:**
        - Ensure the source and target language codes are supported by the M2M100 model.
      operationId: translation_translation__post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/TranslationRequest"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TranslationResponse"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/healthz":
    get:
      summary: Health Check
      description: |-
        Health check endpoint.

        This endpoint is used to check the health of the application.
        A successful response indicates that the application is running as expected.

        Returns:
            dict: A JSON object with a single key `status` with a value of "OK".
      operationId: health_check_healthz_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            "$ref": "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Record:
      properties:
        id:
          type: string
          title: Id
          description: Unique identifier for each record
        text:
          type: string
          title: Text
          description: The text to be translated
      type: object
      required:
      - id
      - text
      title: Record
    TranslationPayload:
      properties:
        fromLang:
          type: string
          title: Fromlang
          description: Source language code (e.g., 'en' for English)
        toLang:
          type: string
          title: Tolang
          description: Target language code (e.g., 'ja' for Japanese)
        records:
          items:
            "$ref": "#/components/schemas/Record"
          type: array
          title: Records
          description: List of records to be translated
      type: object
      required:
      - fromLang
      - toLang
      - records
      title: TranslationPayload
    TranslationRequest:
      properties:
        payload:
          allOf:
          - "$ref": "#/components/schemas/TranslationPayload"
          description: Payload containing all necessary details for the translation
            request
      type: object
      required:
      - payload
      title: TranslationRequest
      example:
        payload:
          fromLang: en
          records:
          - id: '123'
            text: Life is like a box of chocolates.
          toLang: ja
    TranslationResponse:
      properties:
        result:
          items:
            "$ref": "#/components/schemas/Record"
          type: array
          title: Result
          description: List of records containing the translation results
      type: object
      required:
      - result
      title: TranslationResponse
      example:
        result:
        - id: '123'
          text: 人生はチョコレートの箱のようなものだ。
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
