apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation-deployment
  labels:
    app: translation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translation
  template:
    metadata:
      labels:
        app: translation
    spec:
      containers:
      - name: translation
        image: ${REGISTRY_CLUSTER_IP}/translate_service:latest # Please set REGISTRY_CLUSTER_IP before deployment
        ports:
        - containerPort: 9527
        # resources: # Minikube when using the Docker driver doesn't support GPU access
        #   limits:
        #     nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: translation-service
spec:
  type: NodePort
  selector:
    app: translation
  ports:
    - protocol: TCP
      port: 9527
      targetPort: 9527
